### ISSUE TITLE
For different input images

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [alexnaoki/analog-gauge-reader#1]
Hi, 
     I am trying to read the given analog gauge meter. Can you explain the usage guide and suggest changes? 

![4492](https://user-images.githubusercontent.com/28862708/100494102-40a08e80-3179-11eb-807b-63d672f4875b.jpg)

**Comment by alexnaoki** [comment]
To be honest, the code in this repository still needs modification to become user-friendly, however, I suggest the following [repository](https://github.com/intel-iot-devkit/python-cv-samples/tree/master/examples/analog-gauge-reader).
